# Generated by Django 3.2.20 on 2024-03-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0002_auto_20240302_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryperson_profile',
            name='Password',
            field=models.CharField(default=1, max_length=130),
        ),
    ]
