# Generated by Django 3.2.20 on 2024-03-03 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0004_auto_20240303_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryperson_profile',
            name='Password',
        ),
    ]
