# Generated by Django 3.2.20 on 2024-03-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0005_remove_deliveryperson_profile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='Username',
            field=models.CharField(max_length=150),
        ),
    ]
